version: 2.1

orbs:

jobs:
  install:
    working_directory: ~/generator-sicarator
    docker:
      - image: cimg/python:3.11.6-node
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - generator-sicarator-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - generator-sicarator-dependencies-
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: generator-sicarator-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    working_directory: ~/generator-sicarator
    docker:
      - image: cimg/python:3.11.6-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - generator-sicarator-dependencies-{{ checksum "package-lock.json" }}
            - generator-sicarator-dependencies-
      - run:
          name: Run jest
          command: |
            npm run test:ci
          environment:
                  JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

  lint:
    working_directory: ~/generator-sicarator
    docker:
      - image: circleci/node:16.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - generator-sicarator-dependencies-{{ checksum "package-lock.json" }}
            - generator-sicarator-dependencies-
      - run:
          name: Run eslint
          command: |
            npm run lint

workflows:
  version: 2
  sicarator:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
