default_install_hook_types:
- pre-commit
- pre-push
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
- repo: local
  hooks:
  - id: terraform-docs-check
    name: Check terraform docs is up to date
    entry: make docs_check
    language: system
    stages: [ commit ]

  - id: terraform-docs
    name: Update terraform docs (useful if previous hook failed)
    entry: make docs
    language: system
    stages: [ commit ]

  - id: fmt-check
    name: Check formatting
    entry: make fmt_check
    language: system
    stages: [ commit ]

  - id: terraform-fmt
    name: Do formatting (useful if previous hook failed)
    entry: make fmt
    language: system
    stages: [ commit ]

  - id: tflint
    name: Validates all Terraform configuration files with TFlint
    entry: make lint
    language: system
    stages: [ commit ]

  - id: terraform-validate
    name: Validates all Terraform configuration files with TF validate
    entry: make validate
    language: system
    stages: [ commit ]
